numpy kütüphanesi dizi işlemleri hızlandırır.

In [38]:
import numpy as np

array2 isimli bir array oluşturduk ve bunu 3,5 şeklinde 2 boyutlu diziye çevirdik.

In [39]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Vector:",array2)
a = array2.reshape(3,5)
print("two dimensional array:\n",a)

Vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
two dimensional array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Dizi ile ilgili bilgiler

In [40]:
print("shape", a.shape)
print("dimension", a.ndim)
print("data type", a.dtype.name)
print("size:",a.size)
print("type:",type(a))

shape (3, 5)
dimension 2
data type int32
size: 15
type: <class 'numpy.ndarray'>


İki farklı dizi oluşturup bunlarla matematik işlemleri yapabiliriz.

In [41]:
x= np.array([1,2,3])
y= np.array([4,5,6])
print(x+y)
print(x-y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


a dizisini oluşturup d ye kopyaladık. Ardından b ve c değişkenlerini a'ya eşitledik. Bunlar pointer gibi davranır.

In [42]:
a= np.array([1,2,3])
d=a.copy()
print(d)
b=a
c=a
b[0] =5
print(a,b,c)

[1 2 3]
[5 2 3] [5 2 3] [5 2 3]


İlk 4 indexi hızlı bir şekilde yazdırma

In [43]:
a=np.array([1,2,3,4,5,6,7])
print(a[0])
print(a[0:4])

1
[1 2 3 4]


Diziyi terse alma

In [44]:
reverse_array = a[::-1]
print(reverse_array)

[7 6 5 4 3 2 1]


İki boyutlu bir dizi oluşturduk.

In [45]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(b)
print(b[1,1]) 
print(b[:,1]) # bütün dizilerin 1. elemanları
print(b[1,:]) # 1. dizinin bütün elemanları
print(b[1,1:4]) # 1. dizinin 1. elemanından 4. elemanına kadar 
print(b[-1,:]) # son dizinin bütün elemanları
print(b[:,-1]) # bütün satırların son elementi

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]
